name: Deploy static website

env:
  AWS_DEFAULT_REGION: 'ap-southeast-1'
  AWS_CLOUDFRONT_DISTRIBUTION_ID: 'E4LCXFLZPV915'
  staging: 'stag-master.gtemas.com'
  main: 'master.gtemas.com'
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show
        run: |
          echo "=================================="
          echo ${{ env[github.ref_name] }}
