name: Deploy static website

env:
  AWS_DEFAULT_REGION: 'ap-southeast-1'
  AWS_CLOUDFRONT_DISTRIBUTION_ID: 'E4LCXFLZPV915'
  staging: 'stag-master.gtemas.com'
  main: 'master.gtemas.com'
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show
        run: |
          echo "=================================="
          echo ${{ env[github.ref_name] }}
      - name: MS Team notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          overwrite: '{potentialAction: [{"@type": "OpenUri", name: "Repository", targets: [ { os: "default", uri: `${workflow_link}` } ] } ]}'
